name: Deploy Wizard Emergency

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
jobs:
  deploy-wizard-emergency-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Wizard Emergency
      run: pyinstaller wizard_emergency.spec

    - name: Release Windows Build
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: ${{ inputs.tag }}
        overwrite: true
        file_glob: true
  
  deploy-wizard-emergency-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Wizard Emergency
      run: pyinstaller wizard_emergency_mac.spec

    - name: Release macOS Build
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: ${{ inputs.tag }}
        overwrite: true
        file_glob: true

  deploy-wizard-emergency-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Wizard Emergency
      run: pyinstaller wizard_emergency.spec

    - name: Release macOS Build
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: ${{ inputs.tag }}
        overwrite: true
        file_glob: true
