name: On Push to Main Branch
on:
  push:
    branches:
      - main

jobs:
  get-project-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo snap install yq

      - name: Get project version
        id: get_version
        run: |
          VERSION=$(yq '.project.version' pyproject.toml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  create-tag:
    needs: get-project-version
    runs-on: ubuntu-latest
    outputs:
      tag: v${{ needs.get-project-version.outputs.version }}
    steps:
    - name: Create tag if it doesn't exist
      uses: rickstaa/action-create-tag@v1
      with:
        tag: v${{ needs.get-project-version.outputs.version }}
        message: Automated deployment of ${{ github.sha }}
        tag_exists_error: false

  deploy-wizard-emergency-windows:
    needs: create-tag
    uses: ./.github/workflows/call-deploy-wizard-emergency.yml
    with:
      tag: ${{ needs.create-tag.outputs.tag }}
